name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: reactivecircus/android-sdk-manager-action@v4
      with:
        sdk-version: '30.0.3'

    - name: Build APK
      run: ./gradlew assembleRelease  # atau gunakan 'assembleDebug' untuk build debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyVoiceApp-APK
        path: app/build/outputs/apk/release/app-release.apk  # Sesuaikan path dengan output build
