name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adoptopenjdk'
        java-version: '17'

    - name: Install Android SDK
      run: |
        sudo apt update
        sudo apt install -y unzip wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/Android
        yes | $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --licenses
        $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Build APK
      run: ./gradlew assembleRelease  # atau gunakan 'assembleDebug' untuk build debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyVoiceApp-APK
        path: app/build/outputs/apk/release/app-release.apk  # Sesuaikan path dengan output build
